### ISSUE TITLE
Chrashes on large files.

### ISSUE THREAD

**Issue by SammyKnudsen** [zzzprojects/findandreplace#12]
The fnr.exe crashes on large files 2GB.

Tested on several utf-8 xml files.

**Comment by JonathanMagnan** [comment]
Hello @SammyKnudsen ,

We looking at this request. Unfortunately, it will take too much time to make this request as there are several codes to change.

We added this request to our pool list of the request but I don't think it will happen soon.

Best Regards,

Jonathan
