### ISSUE TITLE
user.config

### ISSUE THREAD

**Issue by lollita** [zzzprojects/findandreplace#14]
fnr not not load all setting from load user.config.
f.e. IsKeepModifiedDate, UseEscapeChars, Dir, ExcludeDir
It would be better if instead of saving the configuration in
%USERPROFILE%\AppData\Local\ENTech_Solutions\
save it in the program folder for portability

**Comment by JonathanMagnan** [comment]
Thank you @lollita for your recommendation.

We will think about it as I believe some people will prefer the current solution and for sure, some people will prefer your solution.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @lollita ,

After talking to my developer, we chose of not saving in the program folder.

We prefer to keep the output as only the `executable` alone since there is not a lot of setting.

Best Regards,

Jonathan
