### ISSUE TITLE
Scrolling through results with arrow keys does not update preview

### ISSUE THREAD

**Issue by firstwardo** [zzzprojects/findandreplace#16]
When scrolling through the results list using the arrow keys, the preview does not update to reflect the currently selected item. As far as I know that will only happen when clicking on each item individually.

**Comment by JonathanMagnan** [comment]
Hello @firstwardo ,

Thank you for reporting,

We will check it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @firstwardo ,

The v1.7.7 has been released.

Preview should now work correctly with arrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @firstwardo ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan.
