### ISSUE TITLE
Virus detected when downloading find and replace

### ISSUE THREAD

**Issue by tim5211** [zzzprojects/findandreplace#17]
![fnr-virus](https://user-images.githubusercontent.com/38673703/39158146-881c51fe-479d-11e8-8e7d-c0355f859ec9.png)

Is this a false positive?
I'd really like to use the program to create updated for certain files and you'rs had the best reviews.

**Comment by JonathanMagnan** [comment]
Hello @tim5211 ,

Yes, it's a false positive.

This project has been used by thousands of people already and you have access directly to the source here.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
