### ISSUE TITLE
--defaultEncodingIfNotDetected Not Working

### ISSUE THREAD

**Issue by IBNobody** [zzzprojects/findandreplace#18]
When running the command...

"C:\Tools\fnr.exe" --cl --dir "T:\Foo" --fileMask "*.*" --excludeFileMask "*.dll, *.exe" --includeSubDirectories --useRegEx --skipBinaryFileDetection --defaultEncodingIfNotDetected --find ">aaa" --replace ">bbb"

... the defaultEncodingIfNotDetected switch is not being detected. I get the help output instead.

(Also, if I want to find and replace in a binary, what encoding should I select?)

**Comment by JonathanMagnan** [comment]
Hello @IBNobody ,

I will have my developer to look at it.

Best Regards,

Jonathan

**Comment by IBNobody** [comment]
The defaultEncodingIfNotDetected switch needs an encoding specified in order to work. 

`--defaultEncodingIfNotDetected "Windows-1252"`

I thought this flag meant "use a default encoding hardcoded into the program if the encoding cannot be determined". The actual function of it is "use a user-specified encoding if the encoding cannot be determined automatically.

In my case, I needed `--skipBinaryFileDetection --defaultEncodingIfNotDetected "Windows-1252"` to properly parse binary files.

(Great utility, by the way The only thing it seems to be missing is the use of back-references for regex replacements.)
