### ISSUE TITLE
Backreferencing regexp in replace does not work

### ISSUE THREAD

**Issue by CHRONiCiTY** [zzzprojects/findandreplace#2]
I'd been looking for a commandline tool that could search & replace in regular expressions and thought I'd finally found one.
While finding the text indeed does work using regexp, replacing using regexp does not.

Here's an example of a regexp search:
Original string: <label>$INFO[Window.Property(LatestEpisode.3.EpisodeTitle)]</label>
Search: <label>\$INFO\[Window\.Property\(LatestEpisode\.(\d{1,2})\.EpisodeTitle\)\]<\/label>

Here's the replace bit:
<label>$INFO[Window.Property(LatestEpisode.\1.ShowTitle)]</label>

The "\1" part is backreferencing to the group created in the search string "(\d{1,2})" but fnr just ignores the group and replaces everything with \1 instead of the result from the group.

**Comment by JonathanMagnan** [comment]
Hello @CHRONiCiTY ,

We will start the support on this library next week. We are currently focusing our effort this week to create a website with some documentation.

I have added a task to look at it.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @CHRONiCiTY ,

Sorry for the delay.

The problem since to be caused because of some missing escaped character for `$`, `[`, `]`, `(`, `)`

It seems to work if we escape these special characters

```csharp
"\$INFO\[Window.Property\(LatestEpisode.(\d{1,2}).EpisodeTitle\)\]"
```

Let me know if that helped you.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @CHRONiCiTY ,

We are currently making some issue cleanup.

Feel free to reopen if you believe we closed it by mistake

Best Regards,

Jonathan


---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
