### ISSUE TITLE
Critical Bug: Trying to do a find on a drive root C:\ D:\ causes the program to crash

### ISSUE THREAD

**Issue by PiotrMP006** [zzzprojects/findandreplace#22]
If you select a root folder C:\ D:\ and press Find only or Replace then program crash and close.

Version: 1.7.8.0

**Comment by JonathanMagnan** [comment]
Hello @PiotrMP006 ,

Thank you for reporting, we will look what could cause the issue or if that's a security check to avoid some major mistake.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @PiotrMP006 ,

The v1.7.9 has been released.

The new version should no longer crash but show the error that has been raised.

The error normally happens because of some folder right. Unfortunately, we have no plan to fix this error at this moment.

Let me know if that's fine with you.

Best Regards,

Jonathan

**Comment by PiotrMP006** [comment]
Hi

> The error normally happens because of some folder right. 
Can not you correct this important bug?

> Unfortunately, we have no plan to fix this error at this moment.
Ha ha ha... Find and Replace only in folder not in root disk C: D:...

Are you serious or a joke?

You must be children ...

**Comment by JonathanMagnan** [comment]
Hello @PiotrMP006 ,

Feel free to fix it and make a pull request. We will be happy to merge it ;)

Keep in mind that this product is free for you, but it's not close to being free for me to support.

Only last week, it cost me over $1500 to make a request about the form to be more responsive. So yes, there is some request that we need to skip as we don't have the money nor the time to make them.

Hope you better understand and will never say that kind of thing to someone supporting a FOSS.

As said, feel free to make a pull request with your change.

Best Regards,

Jonathan

**Comment by PiotrMP006** [comment]
The error has still not been corrected !!!


If you select a root folder C:\ D:\ and press Find only or Replace then program crash

"Access to the path "D:\$RECYCLE.BIN\S-1-5-21-...." is danied."

![fnr_access_danied](https://user-images.githubusercontent.com/39049428/43133802-2a392194-8f40-11e8-91de-6ffb36159105.png)
