### ISSUE TITLE
Lacks "exclude directories" options

### ISSUE THREAD

**Issue by danilaml** [zzzprojects/findandreplace#3]
There is no way to exclude certain sub-directories from matching.
This is is very annoying in case you run fnr on a git repo dir, since it also picks up thousands of files in `.git` folder.

**Comment by JonathanMagnan** [comment]
Hello @danilaml ,

Thank you for reporting, we will look at this request to see what we could do.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @danilaml  ,

The v1.7.1 has been released.

A new option named `Exclude Dir` has been added.

Let me know if that answers to your question.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by danilaml** [comment]
@JonathanMagnan I now get
```
System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "FindAndReplace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'FindAndReplace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   в FindAndReplace.App.MainForm.btnFindOnly_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Whenever I try to search something.

**Comment by JonathanMagnan** [comment]
Hello @danilaml ,

My bad, I zipped the wrong file!

The zip has been updated & tested!

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by danilaml** [comment]
@JonathanMagnan Thanks. Looks like it works now. Though I get a lot more binary stuff in the output (mostly png/jpg and other images), than before.

**Comment by JonathanMagnan** [comment]
Hello @danilaml ,

Let me know if you find something about the additional files.

What do you have now exactly you didn't have before? Do you have a way to get us started about this issue?

Best Regards,

Jonathan

_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by danilaml** [comment]
Well, the tool now finds `.png`/`.jpg` files in the dir, even though they should be skipped (imho). But maybe it did so before and I just don't remember.

**Comment by JonathanMagnan** [comment]
Hmmm maybe ;)

We will try it next week.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @danilaml ,

We looked at this issue today about additional files.

We believe it's probably only because the `Skip binary file detection` was unchecked and it's now checked.

When checked, binary file is not checked and return file such as image.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzpr
