### ISSUE TITLE
Element overflow problem

### ISSUE THREAD

**Issue by Ngranger** [zzzprojects/findandreplace#4]
I've only recently started using your wonderful product BUT I quickly noticed an issue while the program was both maximized and un-maximized on screens with a pixel height of 768.  The frame where the text preview for the results is basically cropped off by the bottom edge of the program's window.

**Comment by JonathanMagnan** [comment]
Hello @Ngranger ,

Thank you for reporting,

We will look at this issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Ngranger  ,

The v1.7.2 has been released,

We have slightly reduced the size of the WinForm. However, I don't think we will do anything more for a very resolution like this one.

Best Regards,

Jonathan

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Ngranger ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,
