### ISSUE TITLE
Lack of Whole Words option

### ISSUE THREAD

**Issue by Ngranger** [zzzprojects/findandreplace#5]
In most find & replace dialogs I've seen they have an option to limit searches to only whole words.

**Comment by JonathanMagnan** [comment]
Hello @Ngranger ,

Thank you for your suggestion,

We will check if we want or not to support this options.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Ngranger ,

We will probably eventually improve the tools but currently, we internally agreed to instead propose to use regex instead for this kind of request to get more flexibility.

By example, if you want an exact match word: `\bhello*\b`

Let me know if that answer to this issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Ngranger ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
