### ISSUE TITLE
Relative directory path

### ISSUE THREAD

**Issue by nminkov** [zzzprojects/findandreplace#8]
Hello, 
Thank you for the useful program.

I've encountered 2 major issues on the :

1. It does not seem possible to use relative directories, in GUI and command line.
2. After command line execution, the program always waits for ENTER to close, which is bad for  automation an use in scripts.

Will be great if you can fix these issues.

Thanks

**Comment by nminkov** [comment]
Point 2 only happens on error.  Works as expected on success

**Comment by JonathanMagnan** [comment]
Hello @nminkov ,

Thank you for reporting.

We will try to look at the relative directory feature this week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by nminkov** [comment]
Thank you Jonathan

**Comment by JonathanMagnan** [comment]
Hello @nminkov ,

The v1.7.2 has been released,

It should now support relative path.

Let us know if that work as expected.

Best Regards,

Jonathan

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by nminkov** [comment]
Great. Thank you guys, will test it tomorrow.

**Comment by JonathanMagnan** [comment]
Hello @nminkov ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
